# Generated by Django 4.1 on 2022-08-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat', '0013_alter_products_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_image_meats'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sku',
            field=models.IntegerField(default=853),
        ),
    ]
