# Generated by Django 4.0.6 on 2022-08-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat', '0018_alter_products_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='unic',
            field=models.CharField(default='m', max_length=1),
        ),
        migrations.AlterField(
            model_name='products',
            name='sku',
            field=models.IntegerField(default=1052),
        ),
    ]
