# Generated by Django 4.1 on 2022-08-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat', '0020_alter_products_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sku',
            field=models.IntegerField(default=1838),
        ),
    ]
