# Generated by Django 4.0.6 on 2022-09-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat', '0027_alter_products_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products_image_meats'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sku',
            field=models.IntegerField(default=1472),
        ),
    ]
