# Generated by Django 4.0.6 on 2022-09-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat', '0051_alter_products_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='sku',
            field=models.IntegerField(default=880),
        ),
    ]
