# Generated by Django 4.0.6 on 2022-09-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat', '0085_alter_products_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='unic',
        ),
        migrations.AlterField(
            model_name='products',
            name='sku',
            field=models.IntegerField(default=128),
        ),
    ]
