# Generated by Django 4.0.6 on 2022-09-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('sku', models.IntegerField(default=361, unique=True)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_image_drinks')),
                ('unic', models.CharField(default='d', max_length=1)),
                ('category', models.IntegerField(choices=[[1, 'Carne'], [1, 'Panaderia'], [3, 'Bebida']], default=1)),
            ],
        ),
    ]
