# Generated by Django 4.0.6 on 2022-09-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_products_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='sku',
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.IntegerField(choices=[[1, 'Carne'], [2, 'Panaderia'], [3, 'Bebida']], default=1),
        ),
    ]
