# Generated by Django 4.0.6 on 2022-09-03 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_products_sku_alter_products_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
