# Generated by Django 4.0.6 on 2022-08-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panificacion', '0002_panes_stock_alter_panes_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panes',
            name='sku',
            field=models.IntegerField(default=746),
        ),
    ]
