# Generated by Django 4.1 on 2022-09-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_text_contact_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
