# Generated by Django 4.1 on 2022-08-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0003_alter_bakeries_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bakeries',
            options={'verbose_name_plural': 'Bakeries'},
        ),
        migrations.AlterField(
            model_name='bakeries',
            name='sku',
            field=models.IntegerField(default=1146),
        ),
    ]
