# Generated by Django 4.1 on 2022-08-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0012_alter_bakeries_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakeries',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_image_bakeries'),
        ),
        migrations.AlterField(
            model_name='bakeries',
            name='sku',
            field=models.IntegerField(default=371),
        ),
    ]
