# Generated by Django 4.0.6 on 2022-08-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0017_alter_bakeries_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakeries',
            name='unic',
            field=models.CharField(default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='bakeries',
            name='sku',
            field=models.IntegerField(default=1251),
        ),
    ]
