# Generated by Django 4.1 on 2022-08-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0024_alter_bakeries_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakeries',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products_image_bakeries'),
        ),
        migrations.AlterField(
            model_name='bakeries',
            name='sku',
            field=models.IntegerField(default=353),
        ),
    ]
