# Generated by Django 4.0.6 on 2022-09-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0084_alter_bakeries_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakeries',
            name='unic',
        ),
        migrations.AlterField(
            model_name='bakeries',
            name='sku',
            field=models.IntegerField(default=1217),
        ),
    ]
