# Generated by Django 4.0.6 on 2022-08-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0002_remove_bebidas_category_bebidas_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebidas',
            name='sku',
            field=models.IntegerField(default=1833),
        ),
    ]
