# Generated by Django 4.0.6 on 2022-08-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0005_alter_bebidas_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebidas',
            name='sku',
            field=models.IntegerField(default=754),
        ),
    ]
