# Generated by Django 4.0.6 on 2022-08-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('sku', models.IntegerField(default=1509)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
