# Generated by Django 4.1 on 2022-08-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0003_alter_drinks_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drinks',
            options={'verbose_name_plural': 'Drinks'},
        ),
        migrations.AlterField(
            model_name='drinks',
            name='sku',
            field=models.IntegerField(default=669),
        ),
    ]
