# Generated by Django 4.1 on 2022-08-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0011_alter_drinks_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinks',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_image_meats'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='sku',
            field=models.IntegerField(default=532),
        ),
    ]
