# Generated by Django 4.0.6 on 2022-09-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0026_alter_drinks_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products_image_drinks'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='sku',
            field=models.IntegerField(default=1703),
        ),
    ]
