# Generated by Django 4.0.6 on 2022-09-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0083_alter_drinks_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinks',
            name='unic',
        ),
        migrations.AlterField(
            model_name='drinks',
            name='sku',
            field=models.IntegerField(default=707),
        ),
    ]
