# Generated by Django 4.1 on 2022-09-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0084_remove_drinks_unic_alter_drinks_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='sku',
            field=models.IntegerField(default=1687),
        ),
    ]
